spring:
  config:
    import: optional:configserver:${CONFIGSERVER_URL}
    activate:
      on-profile: eureka
  autoconfigure:
    exclude:
      # Exclusion for kubernetes
      - org.springframework.cloud.kubernetes.discovery.reactive.KubernetesReactiveDiscoveryClientAutoConfiguration
      - org.springframework.cloud.kubernetes.discovery.KubernetesDiscoveryClientAutoConfiguration
      - org.springframework.cloud.kubernetes.discovery.KubernetesCatalogWatchAutoConfiguration