logging:
  level:
    root: info
    org.springframework.cloud.config.server: info

spring:
  webflux:
    base-path: /apilabtech
  application:
    name: apigateway
    cloud:
      loadbalancer:
        ribbon:
          enabled: false
  cloud:
    gateway:
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

server:
  port: ${APPLICATION_HOST_PORT:8080}

management:
  endpoint:
    gateway:
      enabled: true
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "info,health,metrics,mappings,gateway"

---
spring:
  config:
    import: optional:configserver:${CONFIGSERVER_URL}
    activate:
      on-profile: eureka
  autoconfigure:
    exclude:
      # Exclusion for kubernetes
      - org.springframework.cloud.kubernetes.discovery.reactive.KubernetesReactiveDiscoveryClientAutoConfiguration
      - org.springframework.cloud.kubernetes.discovery.KubernetesDiscoveryClientAutoConfiguration
      - org.springframework.cloud.kubernetes.discovery.KubernetesCatalogWatchAutoConfiguration

---
spring:
  config:
    activate:
      on-profile: kubernetes
  autoconfigure:
    exclude:
      # Exclusion for Eureka client
      - org.springframework.cloud.netflix.eureka.reactive.EurekaReactiveDiscoveryClientConfiguration
      - org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
      - org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration